name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - master  

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Substitua por seu script de build, se necessário

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy via FTP
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u u352176227,$FTP_PASSWORD -e "set ssl:verify-certificate no; mirror -R ./dist/ public_html/; quit" ftp://185.245.180.108
